// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYAPhgW3Z7n_z0luHinH1iu5bAGxYRoIo',
    appId: '1:826832828876:web:12fae6adcf72d22e3c0569',
    messagingSenderId: '826832828876',
    projectId: 'findmykidsauth',
    authDomain: 'findmykidsauth.firebaseapp.com',
    storageBucket: 'findmykidsauth.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5DRD8qJuPVyGzSLiCJJgLaMshbLjIvDQ',
    appId: '1:826832828876:android:5e8d008fb0bcc9973c0569',
    messagingSenderId: '826832828876',
    projectId: 'findmykidsauth',
    storageBucket: 'findmykidsauth.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANa0NANf1brVso0BekehPd2o6-6F3IXc8',
    appId: '1:826832828876:ios:8004a8e3ea9f7cea3c0569',
    messagingSenderId: '826832828876',
    projectId: 'findmykidsauth',
    storageBucket: 'findmykidsauth.appspot.com',
    iosBundleId: 'com.example.findMyKids',
  );
}
